### ISSUE TITLE
Custom error message

### ISSUE THREAD

**Issue by vcernik** [nepada/phone-number-input#155]
Hi, what's the best way to set a custom error message?
I found this: https://github.com/nepada/phone-number-input/blob/449877a59fd8cfa3c48c951c7ca504602f0f8b8d/src/PhoneNumberInput/PhoneNumberInput.php#L32
but I am not able to put a new message into config... :-(

**Comment by xificurk** [comment]
You can configure it in [DI extension config](https://doc.nette.org/en/forms/configuration) same as any other default validation message, or manually set the value to `Nette\Forms\Validator::$messages`.

**Comment by vcernik** [comment]
@xificurk 

aaa, I was trying to do
`Nepada\PhoneNumberInput\Validator::validatePhoneNumber: 'Vyplňte, prosím, telefonní číslo ve správném tvaru.''`

but correct is
`Nepada\PhoneNumberInput\PhoneNumberInput::VALID: 'Vyplňte, prosím, telefonní číslo ve správném tvaru.'`

Maybe some temporary brain blackout :D Thanks!
